### ISSUE TITLE
errors in cronjobs

### ISSUE THREAD

**Issue by loeken** [k8sonlab/publiccharts#14]
found another error in the cronjobs - any insight on the tty used here? 

```
Defaulted container "photos-librephotos" out of: photos-librephotos, check-postgres-ready (init)
Unable to use a TTY - input is not a terminal or the right kind of file
Traceback (most recent call last):
  File "/code/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.9/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/dist-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/code/api/apps.py", line 10, in ready
    build_index.delay()
  File "/usr/local/lib/python3.9/dist-packages/rq/decorators.py", line 64, in delay
    return queue.enqueue_call(f, args=args, kwargs=kwargs,
  File "/usr/local/lib/python3.9/dist-packages/django_rq/queues.py", line 68, in enqueue_call
    return self.original_enqueue_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django_rq/queues.py", line 64, in original_enqueue_call
    return super(DjangoRQ, self).enqueue_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rq/queue.py", line 406, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/usr/local/lib/python3.9/dist-packages/rq/queue.py", line 573, in enqueue_job
    pipe.execute()
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 2061, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1392, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 626, in connect
    self.on_connect()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 716, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 842, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.
command terminated with exit code 1
```

**Comment by varet80** [comment]
The error is result of wrong password of Redis. The crobjob just executes a command on the backend container (kubectl exec). I suggest to check backend container logs.

Tty has no link to this problem

**Comment by varet80** [comment]
@loeken can I close this issue?

**Comment by varet80** [comment]
Closing this, as almost 1 year no reactions
